[workspace]
resolver = "2"
members = ["graphql-http", "examples/example-server"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/miqui/graphql-http-rust"
keywords = ["graphql", "http", "spec", "conformance", "over-http"]
categories = ["network-programming", "web-programming", "parser-implementations"]